# https://quarto.org/docs/reference/formats/markdown/gfm.html
project:
  title: "python applied machine learning"
  output-dir: docs
  render:
    - "**/*.ipynb"
    - "!source" # Exclude source

code-fold: false
format: gfma # GitHub Flavored Markdown
number-sections: true
toc: true
